### PR TITLE
Added new features and automated installation script (introduces -d flag to output only domains)

### LINKED ISSUE #5: error when run
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4e8cc6]

goroutine 132 [running]:
net.(*Resolver).lookupAddr(0x0, 0x590ec0, 0xc42001a088, 0xc42001aad0, 0xc, 0x4297e9, 0x8, 0xc420058080, 0x0, 0xc4200eeef0)
        /usr/lib/go-1.10/src/net/lookup_unix.go:189 +0x26
net.(*Resolver).LookupAddr(0x0, 0x590ec0, 0xc42001a088, 0xc42001aad0, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/lookup.go:390 +0x5a
main.worker(0xc42001aad0, 0xc, 0xc42001a2e0, 0xc420064120)
        /root/go/src/github.com/hakluke/hakrevdns/main.go:35 +0xca
created by main.main
        /root/go/src/github.com/hakluke/hakrevdns/main.go:57 +0x17e

```

### PR DESCRIPTION
**Pull request by hackerpain**
# Feature add and install script
 - Ability to output only domains with ```-d``` flag: Useful to check working domains, and so on
 - Added automated installation script for linux environment that installs both golang (if not already installed) and the script (Fix #5 )

### CODE REVIEW

**Review by hackerpain — COMMENTED** [review]
updated docs

**Comment by hackerpain** [comment]
@hakluke can this be merged?

**Comment by hakluke** [comment]
Hey @hackerpain! Sorry I've been so slack on getting to PRs.
I think some other changes have been made since you sent this through - is there any chance you can resolve these conflicts and test? I can merge it as soon as you're done :)

I'll also put a shoutout on the README if you're keen!

**Comment by hackerpain** [comment]
> I think some other changes have been made since you sent this through - is there any chance you can resolve these conflicts and test? I can merge it as soon as you're done :)

Have done the necessary changes, to resolve the conflicts, and updated it.
As of now, GitHub shows the *conflict* because I imported ```strings``` and added an ```if``` block to trim the trailing ```.``` from the output (domains), so that its easier to pass the stdin to tools like ```httprobe```, you may have a look at that, but I feel its okay to merge it now.
I have checked & it works fine =)

> I'll also put a shoutout on the README if you're keen!

Sure, you can put a shout-out, that would be great!
You can make the credit to [SaveBreach](http://twitter.com/savebreach) :)

**Comment by hakluke** [comment]
Merged, thank you!

**Pull request merged**
